.TH WHATWEB 1 "April 5th, 2011"
.SH NAME
WhatWeb \- Web scanner to identify what websites are running.
.SH SYNOPSIS
.B whatweb
.RI [ options ] 
.RI <URLs>

.br
.SH DESCRIPTION
.PP
WhatWeb identifies websites. It's goal is to answer the question, "What is that Website?". WhatWeb recognises web technologies including content management systems (CMS), blogging platforms, statistic/analytics packages, JavaScript libraries, web servers, and embedded devices. WhatWeb has over 900 plugins, each to recognise something different. WhatWeb also identifies version numbers, email addresses, account ID's, web framework modules, SQL errors, and more.

WhatWeb can be stealthy and fast, or thorough but slow. WhatWeb supports an aggression level to control the trade off between speed and reliability. When you visit a website in your browser, the transaction includes many hints of what web technologies are powering that website. Sometimes a single webpage visit contains enough information to identify a website but when it does not, WhatWeb can interrogate the website further. The default level of aggression, called 'passive', is the fastest and requires only one HTTP request of a website. This is suitable for scanning public websites. More aggressive modes were developed for in penetration tests.

Most WhatWeb plugins are thorough and recognise a range of cues from subtle to obvious. For example, most WordPress websites can be identified by the meta HTML tag, e.g. '<meta name="generator" content="WordPress 2.6.5">', but a minority of WordPress websites remove this identifying tag but this does not thwart WhatWeb. The WordPress WhatWeb plugin has over 15 tests, which include checking the favicon, default installation files, login pages, and checking for "/wp-content/" within relative links.

.TP
.B
Features:
.TP
	* Over 1000 plugins
.TP
	* Control the trade off between speed/stealth and reliability
.TP
	* Performance tuning. Control how many websites to scan concurrently.
.TP
	* Multiple log formats: Brief (greppable), Verbose (human readable), XML, JSON, MagicTree, RubyObject, MongoDB, SQL.
.TP
	* Proxy support including TOR
.TP
	* Custom HTTP headers
.TP
	* Basic HTTP authentication
.TP
	* Control over webpage redirection
.TP
	* Nmap-style IP ranges
.TP
	* Fuzzy matching
.TP
	* Result certainty awareness
.TP
	* Custom plugins defined on the command line


.SH OPTIONS
.TP
.B \<URLs\>
Enter URLs, filenames or nmap-format IP ranges. Use /dev/stdin to pipe HTML directly
.TP
.B \-\-input-file=FILE \-i
Identify URLs found in FILE
.TP
.B \-\-aggression \-a
1 (Stealthy) - Makes one HTTP request per target. Also follows redirects.

2 (Unused) - 

3 (Aggressive) - Can make a handful of HTTP requests per target. This triggers aggressive plugins for targets only when those plugins are identified with a level 1 request first.

4 (Heavy) - Makes a lot of HTTP requests per target. Aggressive tests from
 all plugins are used for all URLs.

.TP
.B \-\-list-plugins \-l
List the plugins
.TP
.B \-\-plugins \-p
Comma delimited set of selected plugins. Default is all.
 Each element can be a directory, file or plugin name and
 can optionally have a modifier, eg. + or -
 Examples: +/tmp/moo.rb,+/tmp/foo.rb
 title,md5,+./plugins-disabled/
 ./plugins-disabled,-md5
.TP
.B \-\-info-plugins \-I
Display information for all plugins. Optionally search
 with keywords in a comma delimited list.
.TP
.B \-\-grep \-g
Search for a string. Reports in a plugin called Grep
.TP
.B \-\-colour=[WHEN] \-\-color=[WHEN]
control whether colour is used. WHEN may be "never", "always", or "auto"
.TP
.B \-\-log-verbose=FILE
Log verbose output
.TP
.B \-\-quiet, \-q
Do not display brief logging to STDOUT
.TP
.B \-\-log-brief=FILE
Log brief, one-line output
.TP
.B \-\-log-xml=FILE
Log XML format
.TP
.B \-\-log-json=FILE
Log JSON format
.TP
.B \-\-log\-sql=FILE
Log SQL INSERT statements
.TP
.B \-\-log\-sql\-create=FILE
Create SQL database tables
.TP
.B \-\-log-json-verbose=FILE
Log JSON Verbose format
.TP
.B \-\-log-magictree=FILE
Log MagicTree XML format
.TP
.B \-\-log-object=FILE
Log Ruby object inspection format
.TP
.B \-\-log-mongo-database=NAME
Name of the MongoDB database
.TP
.B \-\-log-mongo-collection=NAME
Name of the MongoDB collection. Default: whatweb
.TP
.B \-\-log-mongo-host=NAME
MongoDB hostname or IP address. Default: 0.0.0.0
.TP
.B \-\-log-mongo-username=NAME
MongoDB username. Default: nil
.TP
.B \-\-log-mongo-password=NAME
MongoDB password. Default: nil
.TP
.B \-\-log-errors=FILE
Log errors
.TP
.B \-\-no-errors
Suppress error messages
.TP
.B \-\-user-agent \-U
Identify as user-agent instead of WhatWeb/VERSION.
.TP
.B \-\-user \-u <user:password>
HTTP basic authentication
.TP
.B \-\-header \-H
Add an HTTP header. eg "Foo:Bar". Specifying a default
 header will replace it. Specifying an empty value, eg.
 "User-Agent:" will remove the header.
.TP
.B \-\-max-threads \-t
Number of simultaneous threads. Default is 25.
.TP
.B \-\-follow-redirect=WHEN
Control when to follow redirects. WHEN may be "never", "http-only", "meta-only", "same-site", "same-domain" or "always"
.TP
.B \-\-max-redirects=NUM	
Maximum number of contiguous redirects. Default: 10
.TP
.B \-\-proxy <hostname[:port]>
Set proxy hostname and port (default: 8080)
.TP
.B \-\-proxy-user <username:password>
Set proxy user and password
.TP
.B \-\-open-timeout
Time in seconds. Default: 15
.TP
.B \-\-read-timeout
Time in seconds. Default: 30
.TP
.B \-\-wait=SECONDS
Wait SECONDS between connections.
This is useful when using a single thread.
.TP
.B \-\-custom-plugin
Define a custom plugin call Custom,
Examples: ":text=>'powered by abc'"
":regexp=>/powered[ ]?by ab[0-9]/"
":ghdb=>'intitle:abc "powered by abc"'"
":md5=>'8666257030b94d3bdb46e05945f60b42'"
"{:text=>'powered by abc'},{:regexp=>/abc [ ]?1/i}"
.TP
.B \-\-dorks <plugin name>
List google dorks for the selected plugin
.TP
.B \-\-url-prefix
Add a prefix to target URLs
.TP
.B \-\-url-suffix
Add a suffix to target URLs
.TP
.B \-\-url-pattern
Insert the targets into a URL. Requires --input-file,
eg. www.example.com/%insert%/robots.txt
.TP
.B \-\-help \-h
Display usage
.TP
.B \-\-verbose \-v
Increase verbosity (recommended), use twice for debugging.
.TP
.B \-\-debug
Raise errors in plugins.
.TP
.B \-\-version
Display version information.

.SH EXAMPLES
.TP
.B Passive:
 whatweb example.com
.TP
.B Passive (Verbose):
 whatweb -v example.com
.TP
.B Aggressive:
 whatweb -a 3 example.com
.TP
.B IP Ranges
 whatweb 192.168.1.0/24

.SH BUGS
Report bugs and feature requests to https://github.com/urbanadventurer/WhatWeb

.SH AUTHOR
WhatWeb was written by Andrew Horton aka urbanadventurer, and Brendan Coles.

.SH HOMEPAGE
http://www.morningstarsecurity.com/research/whatweb
.PP

