#!/bin/bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This file is part of WhatWeb and may be subject to
# redistribution and commercial restrictions. Please see the WhatWeb
# web site for more information on licensing and terms of use.
# http://www.morningstarsecurity.com/research/whatweb
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Hunter finds web applications with Google then fingerprints them with WhatWeb
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
VERSION="0.1.1"
AUTHOR="Brendan Coles [ itsecuritysolutions.org ]"

# Hunter settings
VERBOSE="TRUE"
LIST=""

# WhatWeb settings
AGGRESSION="1"
USERAGENT="Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341"
PROXYUSER=""  # "username:password" Set proxy user and password
PROXY=""      # "hostname:port"     Set proxy hostname and port

# GGGooglescan settings
WAIT="0"
DEPTH="5"
GSCAN_QUIET="" # gggooglescan's quiet mode is broken in v0.4
#GSCAN_QUIET="-q"

# Check for WhatWeb in the current working directory
WHATWEB="./whatweb"
if [[ ! -e "$WHATWEB" ]]; then
	# Check for WhatWeb in the parent directory
	WHATWEB="../whatweb"
	if [[ ! -e "$WHATWEB" ]]; then
		# Check if WhatWeb is installed
		WHATWEB=`which whatweb 2>/dev/null`
		if [[ -z "$WHATWEB" ]]; then
			echo "[!] Fatal Error: WhatWeb must be in the parent directory, in the current working directory or installed. Homepage: http://www.morningstarsecurity.com/research/whatweb"
			exit 1
		fi
	fi
fi


# Quit if gggooglescan is not in the current working directory
GOOGLESCAN="./gggooglescan"
if [[ ! -e "$GOOGLESCAN" ]]; then
	echo "[!] Fatal Error: Could not locate gggooglescan in the current working directory. Homepage: http://www.morningstarsecurity.com/research/gggooglescan"
	exit 1
fi


# Show usage and quit
function usage {

LRED="\033[1;32m"
DRED="\033[0;32m"
NOCOLOR="\033[0m"

echo -e "
$LRED         @@@  @@@   @@@  @@@   @@@  @@@   @@@@@@@   @@@@@@@@   @@@@@@@ 
$LRED         @@!  @@@   @@!  @@@   @@!@!@@@     @@!     @@!        @@!  @@@
$DRED         @!@!@!@!   @!@  !@!   @!@@!!@!     @!!     @!!!:!     @!@!!@! 
$DRED         !!:  !!!   !!:  !!!   !!:  !!!     !!:     !!:        !!: :!! 
$DRED          :   : :    :.:: :    ::    :       :      : :: :::    :   : :
$NOCOLOR
Hunter - Finds web applications with Google then fingerprints them with WhatWeb
Version $VERSION by $AUTHOR

Usage:   ./hunter [options] <Application Name>
Example: ./hunter wordpress

Options:
  -l KEYWORD		List supported applications. Filter by keyword.
			Use \".\" to list all applications.
  -d NUM		Depth of results. Num of pages to return. Default: 5
  -a AGGRESSION		Set WhatWeb aggression level. Default: 1 (passive)
  -u USER-AGENT		Set WhatWeb user agent
  -w SECONDS		Wait for SECONDS between each Google query. Default: 0
  -h			This help info
  -q			Quiet. Turn off comment lines.
"
}


# Command line options
while getopts 'd:a:u:w:l:qh' OPTION
do
 case $OPTION in
 h) usage; exit ;;
 d) DEPTH=$OPTARG ;;
 a) AGGRESSION=$OPTARG ;;
 u) USERAGENT=$OPTARG ;;
 w) WAIT=$OPTARG ;;
 q) VERBOSE="FALSE" ;;
 l) LIST=$OPTARG ;;
 esac
done
shift $(($OPTIND -1 ))

# List applications
if [[ ! -z "$LIST" ]]; then
	if [[ "$VERBOSE" == "TRUE" ]]; then
		echo "[+] Listing applications matching \"$LIST\"" >&2
	fi
	"$WHATWEB" -I | grep "Dorks:" -B 5 | grep -E "^(\w)" | grep -i "$LIST"
	exit
fi

# Show usage when no arguments are provided
if [[ -z "$1" ]]; then
	usage
        exit 1
fi

# Get dorks from WhatWeb
if [[ "$VERBOSE" == "TRUE" ]]; then
	echo "[+] Loading Google queries for $1" >&2
fi

DORKS=`"$WHATWEB" -g "$1"`

# Quit if no dorks were returned
if [[ -z "$DORKS" ]]; then
	if [[ "$VERBOSE" == "TRUE" ]]; then
		echo "[-] No Google queries were found. Try ./hunter -l $1" >&2
	fi
	exit 1
fi

# Show google dorks
if [[ "$VERBOSE" == "TRUE" ]]; then
	echo "[+] Found the following Google queries:" >&2
	echo "$DORKS"
	echo "[+] Searching Google for instances of $1:" >&2
fi

# Show google query URLs
if [[ "$VERBOSE" == "TRUE" ]]; then
	GSCAN_QUIET=""
fi

# Pipe dorks to gggooglescan then pipe the results to WhatWeb
echo "$DORKS" | while read LINE ; do "$GOOGLESCAN" $GSCAN_QUIET -d "$DEPTH" -s "$WAIT" "$LINE"; done | egrep -v "^#" | "$WHATWEB" -a "$AGGRESSION" -U "$AGENT" -i /dev/stdin --proxy "$PROXY" --proxy-user "$PROXYUSER" --log-brief="$1.log" -p "$1" | grep -i "$1"

# Show log message
if [[ "$VERBOSE" == "TRUE" ]]; then
	echo "[+] Wrote output to $1.log" >&2
fi

