#!/bin/bash
##
# This script creates WhatWeb plugins from the WAFP fprints_wafp.db file
# Version 0.2 # Written by: Brendan Coles <bcoles@gmail.com> (c) 2010-09-08
##
# Declerations
##
ERROR_ID=0
DATABASE="fprints_wafp.db"

# Check if argument 1 was supplied
if [ $1 ]
then
	DATABASE=$1
fi

# Check if argument 1 is a valid file
if [ ! -f $DATABASE ]
then
	ERROR_ID=404
else
	# Check if the file is a valid SQLITE file
	SQLITE_DB=`head --lines 1 $DATABASE | grep "SQLite format" | wc -l`
	if [ $SQLITE_DB -eq 0 ]
	then
		ERROR_ID=204
	fi
fi

# Show usage and quit on error
if [ $ERROR_ID -gt 0 ]
then
	echo "/******************"
	echo "* WAFP to WhatWeb *"
	echo "******************/"
	echo "This script creates WhatWeb plugins from the WAFP fprints_wafp.db file."
	echo "Written by: Brendan Coles <bcoles@gmail.com> (c) 2010-09-06"
	echo
	echo "Usage:"
	echo "$0 /path/to/fprints_wafp.db"
	echo
	echo "Example:"
	echo "$0 fprints_wafp.db"
	echo
	exit
fi

################################################################################
# Plugin creation and WAFP DB hash extraction
################################################################################


################################################################################
# DRUPAL
################################################################################

# Start plugin
PLUGIN="drupal"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "	m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# FLUXBB
################################################################################


# Start plugin
PLUGIN="fluxbb"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# JOOMLA
################################################################################

# Start plugin
PLUGIN="joomla"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# PHPBB
################################################################################

# Start plugin
PLUGIN="phpBB"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# PHPMYADMIN
################################################################################

# Start plugin
PLUGIN="phpmyadmin"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# PUNBB
################################################################################

# Start plugin
PLUGIN="punbb"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# SERENDIPITY
################################################################################

# Start plugin
PLUGIN="serendipity"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# SMF
################################################################################

# Start plugin
PLUGIN="smf"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# TYPO3
################################################################################

# Start plugin
PLUGIN="typo3"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"


################################################################################
# WORDPRESS
################################################################################

# Start plugin
PLUGIN="wordpress"
echo "[*] Generating $PLUGIN-WAFP.rb plugin . . ."
START=`date +%s`

# Query DB
sqlite3 $DATABASE "SELECT \"if @md5sum == '\",f.csum,\"' then m << {:version=>'\",p.versionstring,\"'} end # \",substr(f.path,3) FROM tbl_fprint as f, tbl_product as p WHERE p.id=f.product_id AND p.name=\"$PLUGIN\" GROUP BY p.name, p.versionstring, f.path;" | sed 's/|//g' > "$PLUGIN-WAFP.tmp.rb"

# Write plugin
LINES=`cat $PLUGIN-WAFP.tmp.rb | wc -l`
echo "##" > "$PLUGIN-WAFP.rb"
echo "# This file is part of WhatWeb and may be subject to" >> "$PLUGIN-WAFP.rb"
echo "# redistribution and commercial restrictions. Please see the WhatWeb" >> "$PLUGIN-WAFP.rb"
echo "# web site for more information on licensing and terms of use." >> "$PLUGIN-WAFP.rb"
echo "# http://www.morningstarsecurity.com/research/whatweb" >> "$PLUGIN-WAFP.rb"
echo "##" >> "$PLUGIN-WAFP.rb"
echo "Plugin.define \"$PLUGIN-WAFP\" do" >> "$PLUGIN-WAFP.rb"
echo "author \"Brendan Coles <bcoles@gmail.com>\"" >> "$PLUGIN-WAFP.rb"
echo "version \"0.1\"" >> "$PLUGIN-WAFP.rb"
echo "description \"This plugin detects Wordpress versions using a port of the WAFP fingerprint database. - homepage: http://www.mytty.org/wafp/\"" >> "$PLUGIN-WAFP.rb"
echo "def passive" >> "$PLUGIN-WAFP.rb"
echo "  m=[]" >> "$PLUGIN-WAFP.rb"
cat $PLUGIN-WAFP.tmp.rb >> "$PLUGIN-WAFP.rb"
echo "m" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"
echo "end" >> "$PLUGIN-WAFP.rb"

# Output elapsed time and total md5 matches
FINISH=`date +%s`
ELAPSED=`expr $FINISH - $START`
unset START
echo "[*] Wrote $LINES md5 matches to $PLUGIN-WAFP.rb in $ELAPSED seconds"



